# Generated by meteor-tupperware quickstart script 0.1.2
# https://github.com/chriswessels/meteor-tupperware

# Inherit from chriswessels/meteor-tupperware image
FROM quay.io/chriswessels/meteor-tupperware

# The maintainer of your app image
MAINTAINER jherr <jherrington@walmartlabs.com>

# (optional) Bake runtime options into your image
ENV MONGO_URL="mongodb://localhost:27017" MONGO_OPLOG_URL="mongodb://oplog_url" ROOT_URL="http://localhost"
